apiVersion: v1
kind: LimitRange
metadata:
 name: workshop-support
 namespace: workshop-support
spec:
 limits:
   - default:
       cpu: 300m
       memory: 400Mi
     defaultRequest:
       cpu: 100m
       memory: 250Mi
     type: Container
