apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: postgresql
  namespace: openshift-operators
spec:
  channel: v5
  name: postgresql
  source: do280-catalog-community
  sourceNamespace: openshift-marketplace
