apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: CHANGE_ME
  namespace: CHANGE_ME
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: CHANGE_ME
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: CHANGE_ME
